/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package co.poynt.samples.hapiApi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import co.poynt.samples.hapiApi.model.Country;
import co.poynt.samples.hapiApi.model.StateProvince;
import java.io.IOException;

/**
 * Address
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Address {
  @SerializedName("type")
  private String type = null;

  @SerializedName("primary")
  private Boolean primary = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("address3")
  private String address3 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("stateProvince")
  private StateProvince stateProvince = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("country")
  private Country country = null;

  public Address type(String type) {
    this.type = type;
    return this;
  }

   /**
   * address type
   * @return type
  **/
  @ApiModelProperty(example = "BUSINESS", value = "address type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Address primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * primary address flag
   * @return primary
  **/
  @ApiModelProperty(example = "true", value = "primary address flag")
  public Boolean isPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  public Address address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * first line of address. typically contains street info
   * @return address1
  **/
  @ApiModelProperty(example = "1234 Park Ave", value = "first line of address. typically contains street info")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public Address address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * second line of address. typically contains apartment info
   * @return address2
  **/
  @ApiModelProperty(example = "APT 505", value = "second line of address. typically contains apartment info")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public Address address3(String address3) {
    this.address3 = address3;
    return this;
  }

   /**
   * third line of address
   * @return address3
  **/
  @ApiModelProperty(value = "third line of address")
  public String getAddress3() {
    return address3;
  }

  public void setAddress3(String address3) {
    this.address3 = address3;
  }

  public Address city(String city) {
    this.city = city;
    return this;
  }

   /**
   * city associated to address
   * @return city
  **/
  @ApiModelProperty(example = "Miami", value = "city associated to address")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Address stateProvince(StateProvince stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * Get stateProvince
   * @return stateProvince
  **/
  @ApiModelProperty(value = "")
  public StateProvince getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(StateProvince stateProvince) {
    this.stateProvince = stateProvince;
  }

  public Address postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * postal or zip code associated to address
   * @return postalCode
  **/
  @ApiModelProperty(example = "33133", value = "postal or zip code associated to address")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public Address country(Country country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public Country getCountry() {
    return country;
  }

  public void setCountry(Country country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.type, address.type) &&
        Objects.equals(this.primary, address.primary) &&
        Objects.equals(this.address1, address.address1) &&
        Objects.equals(this.address2, address.address2) &&
        Objects.equals(this.address3, address.address3) &&
        Objects.equals(this.city, address.city) &&
        Objects.equals(this.stateProvince, address.stateProvince) &&
        Objects.equals(this.postalCode, address.postalCode) &&
        Objects.equals(this.country, address.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, primary, address1, address2, address3, city, stateProvince, postalCode, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    address3: ").append(toIndentedString(address3)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

