/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package co.poynt.samples.hapiApi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * name of profile holder
 */
@ApiModel(description = "name of profile holder")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class Name {
  @SerializedName("salutation")
  private String salutation = null;

  @SerializedName("first")
  private String first = null;

  @SerializedName("middle")
  private String middle = null;

  @SerializedName("last")
  private String last = null;

  public Name salutation(String salutation) {
    this.salutation = salutation;
    return this;
  }

   /**
   * salutation for guest
   * @return salutation
  **/
  @ApiModelProperty(example = "Mr.", value = "salutation for guest")
  public String getSalutation() {
    return salutation;
  }

  public void setSalutation(String salutation) {
    this.salutation = salutation;
  }

  public Name first(String first) {
    this.first = first;
    return this;
  }

   /**
   * first name
   * @return first
  **/
  @ApiModelProperty(example = "Christopher", value = "first name")
  public String getFirst() {
    return first;
  }

  public void setFirst(String first) {
    this.first = first;
  }

  public Name middle(String middle) {
    this.middle = middle;
    return this;
  }

   /**
   * middle name or initial
   * @return middle
  **/
  @ApiModelProperty(example = "M", value = "middle name or initial")
  public String getMiddle() {
    return middle;
  }

  public void setMiddle(String middle) {
    this.middle = middle;
  }

  public Name last(String last) {
    this.last = last;
    return this;
  }

   /**
   * last name
   * @return last
  **/
  @ApiModelProperty(example = "Guest", value = "last name")
  public String getLast() {
    return last;
  }

  public void setLast(String last) {
    this.last = last;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Name name = (Name) o;
    return Objects.equals(this.salutation, name.salutation) &&
        Objects.equals(this.first, name.first) &&
        Objects.equals(this.middle, name.middle) &&
        Objects.equals(this.last, name.last);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salutation, first, middle, last);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Name {\n");
    
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    middle: ").append(toIndentedString(middle)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

