/*
 * HAPI Repository API
 * API for retrieving objects from HAPI repository
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package co.poynt.samples.hapiApi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SearchRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-26T23:47:35.032Z")
public class SearchRequest {
  @SerializedName("offset")
  private Integer offset = null;

  @SerializedName("limit")
  private Integer limit = null;

  @SerializedName("fromDate")
  private String fromDate = null;

  @SerializedName("toDate")
  private String toDate = null;

  @SerializedName("chainCode")
  private String chainCode = null;

  @SerializedName("propertyCode")
  private String propertyCode = null;

  public SearchRequest offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Offset from the beginning of retrieved values. If no offset value has provided then default (0) will be used
   * @return offset
  **/
  @ApiModelProperty(value = "Offset from the beginning of retrieved values. If no offset value has provided then default (0) will be used")
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public SearchRequest limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Limit of records in the response. If no limit provided default (100) will be used
   * @return limit
  **/
  @ApiModelProperty(value = "Limit of records in the response. If no limit provided default (100) will be used")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public SearchRequest fromDate(String fromDate) {
    this.fromDate = fromDate;
    return this;
  }

   /**
   * Last update date (from) in YYYY-MM-DDThh:mm:ss.sssZ format
   * @return fromDate
  **/
  @ApiModelProperty(required = true, value = "Last update date (from) in YYYY-MM-DDThh:mm:ss.sssZ format")
  public String getFromDate() {
    return fromDate;
  }

  public void setFromDate(String fromDate) {
    this.fromDate = fromDate;
  }

  public SearchRequest toDate(String toDate) {
    this.toDate = toDate;
    return this;
  }

   /**
   * Last update date (to) in YYYY-MM-DDThh:mm:ss.sssZ format
   * @return toDate
  **/
  @ApiModelProperty(value = "Last update date (to) in YYYY-MM-DDThh:mm:ss.sssZ format")
  public String getToDate() {
    return toDate;
  }

  public void setToDate(String toDate) {
    this.toDate = toDate;
  }

  public SearchRequest chainCode(String chainCode) {
    this.chainCode = chainCode;
    return this;
  }

   /**
   * Hotel chain code. If left blank, no filtering will be used on this field.
   * @return chainCode
  **/
  @ApiModelProperty(value = "Hotel chain code. If left blank, no filtering will be used on this field.")
  public String getChainCode() {
    return chainCode;
  }

  public void setChainCode(String chainCode) {
    this.chainCode = chainCode;
  }

  public SearchRequest propertyCode(String propertyCode) {
    this.propertyCode = propertyCode;
    return this;
  }

   /**
   * Hotel property code. If left blank, no filtering will be used on this field.
   * @return propertyCode
  **/
  @ApiModelProperty(value = "Hotel property code. If left blank, no filtering will be used on this field.")
  public String getPropertyCode() {
    return propertyCode;
  }

  public void setPropertyCode(String propertyCode) {
    this.propertyCode = propertyCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequest searchRequest = (SearchRequest) o;
    return Objects.equals(this.offset, searchRequest.offset) &&
        Objects.equals(this.limit, searchRequest.limit) &&
        Objects.equals(this.fromDate, searchRequest.fromDate) &&
        Objects.equals(this.toDate, searchRequest.toDate) &&
        Objects.equals(this.chainCode, searchRequest.chainCode) &&
        Objects.equals(this.propertyCode, searchRequest.propertyCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offset, limit, fromDate, toDate, chainCode, propertyCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequest {\n");
    
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    chainCode: ").append(toIndentedString(chainCode)).append("\n");
    sb.append("    propertyCode: ").append(toIndentedString(propertyCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

